# Generated by Django 4.2 on 2023-05-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_alter_file_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontype',
            name='can_be_nested',
            field=models.BooleanField(default=False),
        ),
    ]
